dist: xenial
language: node_js
node_js:
  - 10

before_script:
  - 'npm install -g serverless'
  - 'serverless --version'
  - 'sudo apt-get update && sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg'
  - 'curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null'
  - 'AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list'
  - 'sudo apt-get update && sudo apt-get install azure-cli'
  - 'az --version'
  - 'npm install'
  - 'cd controllers && npm install && cd ..'
  - 'cd integration/azure && npm install && cd ../..'
  - 'cd integration/google && npm install && cd ../..'
  - 'rsync -r controllers/ integration/aws/dependencies/nodejs'
  - 'rsync -r controllers/ integration/azure/controllers'
  - 'rsync -r controllers/ integration/google/controllers'

jobs:
  include:
    - stage: deploy
      name: Deploy Milkbox Funnels Backend to Staging
      env: environment=staging
      script:
        - cd integration/aws
        - serverless deploy -v
        - cd ../..
        - cd integration/azure
        - serverless deploy -v
        - cd ../..
