dist: xenial
language: node_js
node_js:
  - 10

before_script:
  - 'npm install -g serverless'
  - 'serverless --version'
  - 'curl -L https://aka.ms/InstallAzureCli | bash'
  - 'az --version'
  - 'npm install'
  - 'cd controllers && npm install && cd ..'
  - 'cd integration/azure && npm install && cd ../..'
  - 'cd integration/google && npm install && cd ../..'
  - 'rsync -r controllers/ integration/aws/dependencies/nodejs'
  - 'rsync -r controllers/ integration/azure/controllers'
  - 'rsync -r controllers/ integration/google/controllers'

jobs:
  include:
    - stage: deploy
      name: Deploy Milkbox Funnels Backend to Staging
      env: environment=staging
      script:
        - cd integration/aws
        - serverless deploy
        - cd ../..
        - cd integration/azure
        - serverless deploy
        - cd ../..
