service: easyfunnel-backend

provider:
  name: google
  runtime: nodejs10
  region: us-east1
  project: easyfunnel-backend-${opt:stage}
  credentials: ~/.gcloud/credentials-${opt:stage}.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - credentials.json
    - credentials-sample.json
    - credentials-production.json
    - credentials-staging.json
    - package-lock.json
    - package.json

functions:
  register:
    handler: register-${opt:stage}
    events:
      - http: path
  payment:
    handler: payment-${opt:stage}
    events:
      - http: path
  membership:
    handler: membership-${opt:stage}
    events:
      - http: path
  upsell:
    handler: upsell-${opt:stage}
    events:
      - http: path
  changeEmail:
    handler: change-email-${opt:stage}
    events:
      - http: path
