service: easyfunnel-backend

provider:
  name: google
  runtime: nodejs10
  region: us-east1
  project: easyfunnel-backend
  credentials: ~/.gcloud/credentials.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - credentials.json
    - credentials-sample.json

functions:
  processAllFunction:
    handler: process
    events:
      - http: path
