service: mb-funnel-be

provider:
  name: aws
  runtime: nodejs10.x
  profile: m1-profile

# you can add packaging information here
package:
#  include:
#    - include-me.js
#    - include-me-dir/**
  exclude:
    - dependencies/**

layers:
  controllers:
    path: dependencies
    description: Shared library layer

functions:
  auth:
    handler: handlers/auth.handler
    name: auth-${opt:stage}
    description: Function to process steps from funnel
    events:
      - http:
          path: auth
          method: post
          cors: true
    layers:
      - {Ref: ControllersLambdaLayer}

  donate:
    handler: handlers/donate.handler
    name: donate-${opt:stage}
    description: Function to process steps from funnel
    events:
      - http:
          path: donate
          method: post
          cors: true
    layers:
      - {Ref: ControllersLambdaLayer}

  getPlans:
    handler: handlers/get_plans.handler
    name: getPlans-${opt:stage}
    description: Function to process steps from funnel
    events:
      - http:
          path: get_plans
          method: post
          cors: true
    layers:
      - {Ref: ControllersLambdaLayer}

  pay:
    handler: handlers/pay.handler
    name: pay-${opt:stage}
    description: Function to process steps from funnel
    events:
      - http:
          path: pay
          method: post
          cors: true
    layers:
      - {Ref: ControllersLambdaLayer}

  register:
    handler: handlers/register.handler
    name: register-${opt:stage}
    description: Function to process steps from funnel
    events:
      - http:
          path: register
          method: post
          cors: true
    layers:
      - {Ref: ControllersLambdaLayer}

  selectPlan:
    handler: handlers/select_plan.handler
    name: selectPlan-${opt:stage}
    description: Function to process steps from funnel
    events:
      - http:
          path: select_plan
          method: post
          cors: true
    layers:
      - {Ref: ControllersLambdaLayer}

  updateEmail:
    handler: handlers/update_email.handler
    name: updateEmail-${opt:stage}
    description: Function to process steps from funnel
    events:
      - http:
          path: update_email
          method: post
          cors: true
    layers:
      - {Ref: ControllersLambdaLayer}

  upgrade:
    handler: handlers/upgrade.handler
    name: upgrade-${opt:stage}
    description: Function to process steps from funnel
    events:
      - http:
          path: upgrade
          method: post
          cors: true
    layers:
      - {Ref: ControllersLambdaLayer}